default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: klaxon_development
  username: <%= `whoami` %>
  host: localhost
  port: 5432

test:
  <<: *default
  database: klaxon_test
  username: <%= `whoami` %>
  host: localhost
  port: 5432

production:
  <<: *default
  database: <%= ENV.fetch('DB_NAME') %>
  username: <%= ENV.fetch('DB_USER') %>
  password: <%= ENV.fetch('DB_PASSWORD') %>
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  port: 5432
