default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: klaxon_development
  username: <%= `whoami` %>
  host: localhost
  port: 5432

test:
  <<: *default
  database: klaxon_test
  username: <%= `whoami` %>
  host: localhost
  port: 5432

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: "127.0.0.1"
  port: 5432
